services:
  app_hair:
    container_name: ui_hairapp
    build: .
    image: ui_hair:v1
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - uinetwork
    
networks:
  uinetwork:
    driver: bridge
