services:
  universalhair_ui:
    container_name: universalhair_ui
    build: .
    image: universalhair_ui:v1
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet
    
networks:
  internalnet:
    driver: bridge
