services:
  app_hair:
    container_name: ui_hair_app
    build: .
    image: ui_hair_app:v1
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - hairnetwork
    
networks:
  hairnetwork:
    driver: bridge
